"""empty message

Revision ID: 1028fa4578f6
Revises: 164310cca807
Create Date: 2018-03-14 10:23:04.734163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1028fa4578f6'
down_revision = '164310cca807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eca', sa.Column('location', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eca', 'location')
    # ### end Alembic commands ###
