"""empty message

Revision ID: 11007796e0ef
Revises: 8650d3d6ee2f
Create Date: 2018-04-05 17:49:46.465148

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '11007796e0ef'
down_revision = '8650d3d6ee2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eca', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eca', 'is_active')
    # ### end Alembic commands ###
