"""empty message

Revision ID: 1fe86f1c4319
Revises: 59c5b4609f43
Create Date: 2018-03-11 19:11:01.274434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe86f1c4319'
down_revision = '59c5b4609f43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eca', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'eca', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'eca', type_='foreignkey')
    op.drop_column('eca', 'user_id')
    # ### end Alembic commands ###
