"""empty message

Revision ID: 2bb79da2a9bb
Revises: 4dccb08a5265
Create Date: 2018-03-22 12:51:06.485404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb79da2a9bb'
down_revision = '4dccb08a5265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eca', sa.Column('brief_description', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eca', 'brief_description')
    # ### end Alembic commands ###
