"""empty message

Revision ID: 34cf78290a61
Revises: 8063670e794d
Create Date: 2018-03-17 22:45:51.853538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34cf78290a61'
down_revision = '8063670e794d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('attended', sa.Boolean(), nullable=False))
    op.add_column('attendance', sa.Column('week_no', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'week_no')
    op.drop_column('attendance', 'attended')
    # ### end Alembic commands ###
