"""empty message

Revision ID: 4dccb08a5265
Revises: 29b48a96b3ea
Create Date: 2018-03-22 12:11:05.596016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dccb08a5265'
down_revision = '29b48a96b3ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eca', sa.Column('essentials', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eca', 'essentials')
    # ### end Alembic commands ###
