"""empty message

Revision ID: 4f1cba5fc9a4
Revises: b9df2f75896b
Create Date: 2018-03-24 18:26:32.830788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f1cba5fc9a4'
down_revision = 'b9df2f75896b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_eca_uc', 'waiting_list', ['user_id', 'eca_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_eca_uc', 'waiting_list', type_='unique')
    # ### end Alembic commands ###
