"""empty message

Revision ID: 59c5b4609f43
Revises: 6df52d12b4bf
Create Date: 2018-03-10 15:33:44.726806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c5b4609f43'
down_revision = '6df52d12b4bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datetime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=8), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('max_people', sa.Integer(), nullable=True),
    sa.Column('max_waiting_list', sa.Integer(), nullable=True),
    sa.Column('datetime_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['datetime_id'], ['datetime.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eca')
    op.drop_table('datetime')
    # ### end Alembic commands ###
