"""empty message

Revision ID: 79b72d6d57ad
Revises: 2bb79da2a9bb
Create Date: 2018-03-21 18:19:06.981190

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79b72d6d57ad'
down_revision = '2bb79da2a9bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datetime', sa.Column('end_time', sa.Time(), nullable=True))
    op.add_column('datetime', sa.Column('start_time', sa.Time(), nullable=True))
    op.drop_column('datetime', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datetime', sa.Column('time', mysql.TIME(), nullable=True))
    op.drop_column('datetime', 'start_time')
    op.drop_column('datetime', 'end_time')
    # ### end Alembic commands ###
