"""empty message

Revision ID: 8650d3d6ee2f
Revises: b642e452d932
Create Date: 2018-03-25 00:01:21.682802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8650d3d6ee2f'
down_revision = 'b642e452d932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waiting_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('eca_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['eca_id'], ['eca.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'eca_id', name='user_eca_uc')
    )
    op.drop_column('registration', 'in_waiting_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration', sa.Column('in_waiting_list', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_table('waiting_list')
    # ### end Alembic commands ###
