"""empty message

Revision ID: b642e452d932
Revises: 4dd851b14b68
Create Date: 2018-03-24 23:48:02.893132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b642e452d932'
down_revision = '4dd851b14b68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration', sa.Column('in_waiting_list', sa.Boolean(), nullable=True))
    op.drop_column('registration', 'waiting_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration', sa.Column('waiting_list', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('registration', 'in_waiting_list')
    # ### end Alembic commands ###
